### ISSUE TITLE
Add Dependabot to Update Dependencies

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-chat-example#73]
Create a file with the following path: `.github/dependabot.yml`

With the following contents:
```
version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
    timezone: Europe/London
```

Docs: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
